Dateformat: DateENlong
GroundWaterFrom: soilfile
ResultFile: Ex1out
OutputIntervall: 0
InitSelection: 1
SoilFile: soil
WeatherFile: '%s_v3test.csv'
WeatherFileSeperator: 1
WeatherFolder: "0/0_0"
WeatherRootFolder: "/beegfs/common/data/climate/macsur_european_climate_scenarios_v3/testing/corrected2"
WeatherNoneValue: 999.9
WeatherNumHeader: 2
CorrectionPrecipitation: 0
ETpot: 3
CoastDistance: 300
CO2method: 2
CO2concentration: 360
CO2StomataInfluence: 1
StartYear: 1980
EndDate: "12312010"
AnnualOutputDate: "1031"
Latitude: 52.52
LeachingDepth: 15
OrganicMatterMineralProportion: 0.13
NDeposition: 20
PolygonGridFileName: poly
Fertilization: 100
VirtualDateFertilizerPrediction: '--------'
KcFactorBareSoil: 0.4
AnnualAverageTemperature: 8.7
AutoSowingHarvest: 1
AutoFertilization: 1
AutoIrrigation: 0
AutoHarvest: 1
